# Generated by Django 6.0.5 on 2026-06-08 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_emergencyreport_ai_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='last_activity_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='last_risk_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='registration_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='suspension_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='suspension_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='ai_review_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='flag_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='flag_type',
            field=models.CharField(blank=True, choices=[('SPAM', 'Possible Spam'), ('DUPLICATE_REPORT', 'Suspicious Duplicate'), ('REVIEW', 'Needs Review')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='image_content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='needs_verification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='priority_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('EXTREME', 'Extreme')], default='LOW', max_length=10),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='risk_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
