# Generated by Django 6.0.5 on 2026-06-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_otprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='ai_criticality',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='ai_incident_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='ai_priority',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='ai_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='ai_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
