# Generated by Django 6.0.5 on 2026-06-10 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_emergencyreport_ai_criticality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='risk_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='risk_source',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10),
        ),
        migrations.CreateModel(
            name='ReportRiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_risk_level', models.CharField(max_length=10)),
                ('new_risk_level', models.CharField(max_length=10)),
                ('changed_by_role', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_level_changes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_logs', to='api.emergencyreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
